# Generated by Django 5.0.7 on 2024-11-29 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auhtor',
            fields=[
                ('id_author', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('naran_author', models.CharField(max_length=100)),
                ('sexu', models.CharField(choices=[('M', 'Mane'), ('F', 'Feto')], max_length=1)),
                ('email', models.CharField(max_length=20)),
                ('nasaun', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dep', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('naran_dep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id_staff', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('naran_staff', models.CharField(max_length=100)),
                ('sexu', models.CharField(choices=[('M', 'Mane'), ('F', 'Feto')], max_length=1)),
                ('nu_telefone', models.CharField(max_length=11)),
                ('hela_fatin', models.CharField(max_length=49)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('nre', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('naran_estudante', models.CharField(max_length=50)),
                ('sexu', models.CharField(choices=[('M', 'Mane'), ('F', 'Feto')], max_length=1)),
                ('periodo', models.CharField(max_length=4)),
                ('nu_telefone', models.CharField(max_length=11)),
                ('id_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Livru',
            fields=[
                ('id_livru', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('naran_livru', models.CharField(max_length=100)),
                ('data_publish', models.DateField()),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.auhtor')),
            ],
        ),
        migrations.CreateModel(
            name='Empresta',
            fields=[
                ('id_empresta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data_empresta', models.DateField()),
                ('data_devolve', models.DateField()),
                ('nre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.estudante')),
                ('id_livru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.livru')),
                ('id_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.staff')),
            ],
        ),
    ]
