# Generated by Django 5.0.7 on 2025-05-18 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran_admin', models.CharField(default='', max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('foto_profile', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('naran_author', models.CharField(max_length=50)),
                ('data_moris', models.DateField(default='2000-01-01')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('sexu', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4)),
                ('nasaun', models.CharField(default='Timor Leste', max_length=20)),
                ('deskrisaun', models.TextField(default='Hau Gosta Han Hudi :)')),
                ('foto_profile', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dep', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('naran_dep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id_staff', models.AutoField(primary_key=True, serialize=False)),
                ('naran_staff', models.CharField(max_length=100)),
                ('username', models.CharField(default='username', max_length=50)),
                ('password', models.CharField(default='password', max_length=255)),
                ('data_moris', models.DateField(default='2000-01-01')),
                ('sexu', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4)),
                ('nu_telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(default='', max_length=50)),
                ('hela_fatin', models.CharField(max_length=50)),
                ('foto_staff', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('nre', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('naran_estudante', models.CharField(max_length=50)),
                ('sexu', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4)),
                ('periodo', models.CharField(max_length=4)),
                ('nu_telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('hela_fatin', models.CharField(max_length=30)),
                ('id_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Livru',
            fields=[
                ('id_livru', models.AutoField(primary_key=True, serialize=False)),
                ('titulu_livru', models.CharField(max_length=100)),
                ('data_publish', models.DateField(default='2000-01-01')),
                ('nasaun', models.CharField(default='Timor Leste', max_length=20)),
                ('tipu_livru', models.CharField(choices=[('Novel', 'Novel'), ('Light Novel', 'Light Novel'), ('Manga', 'Manga'), ('Education', 'Education'), ('History', 'History'), ('Thesis', 'Thesis'), ('Children', 'Children')], default='Novel', max_length=11)),
                ('foto_livru', models.ImageField(blank=True, upload_to='')),
                ('sypnosis', models.TextField(default='BUKU NE TERBAIIIIKKK !!!')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Empresta',
            fields=[
                ('id_empresta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data_empresta', models.DateField()),
                ('data_devolve', models.DateField()),
                ('nre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.estudante')),
                ('id_livru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.livru')),
                ('id_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
