# Generated by Django 5.0.7 on 2025-05-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livru',
            name='tipu_livru',
            field=models.CharField(choices=[('Novel', 'Novel'), ('Light Novel', 'Light Novel'), ('Manga', 'Manga'), ('Education', 'Education'), ('History', 'History'), ('Thesis', 'Thesis'), ('Children', 'Children')], default='Novel', max_length=11),
        ),
    ]
