# Generated by Django 5.0.7 on 2025-05-18 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinan_periodo', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='estudante',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.periodo'),
        ),
    ]
