# Generated by Django 5.0.7 on 2025-05-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_alter_author_sexu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='sexu',
            field=models.CharField(choices=[('M', 'Mane'), ('F', 'Feto')], max_length=1),
        ),
    ]
