# Generated by Django 5.0.7 on 2025-05-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_periodo_alter_estudante_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='data_moris',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
