# Generated by Django 5.0.7 on 2025-05-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_estudante_data_moris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='data_moris',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
