# Generated by Django 5.0.7 on 2025-01-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_costumuser_admin_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostumUser',
        ),
    ]
