# Generated by Django 5.0.7 on 2025-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_alter_author_sexu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hela_fatin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_staff',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sexu',
            field=models.CharField(choices=[('M', 'Mane'), ('F', 'Feto')], max_length=4),
        ),
    ]
