# Generated by Django 5.0.7 on 2025-01-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_costumuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostumUser',
        ),
    ]
