# Generated by Django 5.0.7 on 2025-05-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_alter_staff_hela_fatin_alter_staff_id_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='data_moris',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
