# Generated by Django 5.0.7 on 2025-01-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_delete_costumuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_user',
        ),
    ]
