# Generated by Django 5.0.7 on 2025-05-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_staff_data_moris'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sexu',
            field=models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4),
        ),
    ]
