# Generated by Django 5.0.7 on 2025-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_staff_email_alter_staff_sexu'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='foto_staff',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
