# Generated by Django 5.0.7 on 2025-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_remove_admin_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
