# Generated by Django 5.0.7 on 2025-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
