# Generated by Django 5.0.7 on 2025-01-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_alter_admin_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
