# Generated by Django 5.0.7 on 2025-01-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_remove_admin_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='is_superuser',
        ),
    ]
