# Generated by Django 5.0.7 on 2025-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
