# Generated by Django 5.0.7 on 2025-04-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_remove_admin_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auhtor',
            new_name='Author',
        ),
    ]
