# Generated by Django 5.0.7 on 2025-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0013_rename_auhtor_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='naran_author',
            field=models.CharField(max_length=50),
        ),
    ]
