# Generated by Django 5.0.7 on 2025-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0013_staff_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='email',
            field=models.EmailField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='sexu',
            field=models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4),
        ),
    ]
