# Generated by Django 5.0.7 on 2025-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0014_alter_author_naran_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id_author',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
