# Generated by Django 5.0.7 on 2025-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0014_estudante_email_alter_estudante_sexu'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='hela_fatin',
            field=models.CharField(default='', max_length=25),
        ),
    ]
