# Generated by Django 5.0.7 on 2025-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_estudante_hela_fatin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='periodo',
            field=models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2024', '2024'), ('2025', '2025')], max_length=4),
        ),
    ]
