# Generated by Django 5.0.7 on 2025-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0016_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='foto_profile',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='author_profile'),
        ),
    ]
