# Generated by Django 5.0.7 on 2025-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0017_author_foto_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='foto_profile',
            field=models.ImageField(blank=True, upload_to='author_profile'),
        ),
    ]
