# Generated by Django 5.0.7 on 2025-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0018_alter_author_foto_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='deskrisaun',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
