# Generated by Django 5.0.7 on 2025-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0019_author_deskrisaun'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='data_moris',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
