# Generated by Django 5.0.7 on 2025-05-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0020_author_data_moris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='deskrisaun',
            field=models.TextField(default='Hau Gosta Han Hudi :)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='foto_profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
