# Generated by Django 5.0.7 on 2025-05-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0021_alter_author_deskrisaun_alter_author_foto_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nasaun',
            field=models.CharField(default='Timor Leste', max_length=20),
        ),
    ]
