# Generated by Django 5.0.7 on 2025-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0022_alter_author_nasaun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(default='emailexample@gmail.com', max_length=50),
        ),
    ]
