# Generated by Django 5.0.7 on 2025-05-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0024_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='foto_profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
