# Generated by Django 5.0.7 on 2025-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0025_admin_user_foto_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='naran_admin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
