# Generated by Django 5.0.7 on 2025-05-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0026_admin_user_naran_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='livru',
            name='foto_livru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='livru',
            name='sypnosis',
            field=models.TextField(default='BUKU NE TERBAIIIIKKK !!!'),
        ),
        migrations.AlterField(
            model_name='livru',
            name='id_livru',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
