# Generated by Django 5.0.7 on 2025-05-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0027_livru_foto_livru_livru_sypnosis_alter_livru_id_livru'),
    ]

    operations = [
        migrations.AddField(
            model_name='livru',
            name='nasaun',
            field=models.CharField(default='Timor Leste', max_length=20),
        ),
    ]
