# Generated by Django 5.0.7 on 2025-05-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0028_livru_nasaun'),
    ]

    operations = [
        migrations.AddField(
            model_name='livru',
            name='tipu_livru',
            field=models.CharField(choices=[('Novel', 'Novel'), ('Light Novel', 'Light Novel'), ('Education', 'Education'), ('History', 'History'), ('Thesis', 'Thesis'), ('Children', 'Children')], default='', max_length=11),
        ),
    ]
