# Generated by Django 5.0.7 on 2025-05-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0029_livru_tipu_livru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livru',
            old_name='naran_livru',
            new_name='titulu_livru',
        ),
    ]
