# Generated by Django 5.0.7 on 2025-05-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0030_rename_naran_livru_livru_titulu_livru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livru',
            name='tipu_livru',
            field=models.CharField(choices=[('Novel', 'Novel'), ('Light Novel', 'Light Novel'), ('Education', 'Education'), ('History', 'History'), ('Thesis', 'Thesis'), ('Children', 'Children')], default='Novel', max_length=11),
        ),
    ]
