# Generated by Django 5.0.7 on 2025-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0031_alter_livru_tipu_livru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livru',
            name='data_publish',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
