# Generated by Django 5.0.7 on 2025-05-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0032_alter_livru_data_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livru',
            name='id_author',
        ),
        migrations.AddField(
            model_name='livru',
            name='id_author',
            field=models.ManyToManyField(to='libraryapp.author'),
        ),
    ]
